### PR TITLE
Semaphore-based sync lock in EconomicalChatGPTTranslatorService

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by rodion-m** [comment]
@MarkCiliaVincenti Thanks a lot for the contributation! I couldn't catch, what is the benefit of `AsyncNonKeyedLocker` under built-in `SemaphoreSlim`?

I'm just trying to understand, is it really costs to add an extra dependency.

**Comment by MarkCiliaVincenti** [comment]
I believe that if you want the method to be truly asynchronous then you should not be using the synchronous lock.

**Comment by rodion-m** [comment]
> I believe that if you want the method to be truly asynchronous then you should not be using the synchronous lock.

It's not always true. In these cases, `lock` is used for a few short operations that run on the CPU, so we don't get some valuable benefits (not to mention that `SemaphoreSlim` also uses a short `lock` under the hood when taking a lock). Also, [there is](https://github.com/rodion-m/ChatGPT_API_dotnet/blob/0ea23f0dc1a696f339a1b1a34f75ce1dbc5bebd1/src/modules/OpenAI.ChatGpt.Modules.Translator/EconomicalChatGPTTranslatorService.cs#L142) a re-entrance, so with `SemaphoreSlim` it highly likely will be broken.

**Comment by MarkCiliaVincenti** [comment]
It indeed would, re-entrance and asynchronous code are always a bit of a nightmare.

**Pull request closed without merging**
